image: Visual Studio 2019

environment:
  WINDOWS: 1

platform: Any CPU
configuration: WindowsRelease

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - dotnet restore FreeserfNet.sln --verbosity normal
  - dotnet msbuild -p:Configuration=WindowsRelease -p:DefineConstants=WINDOWS FreeserfNet.sln
  - dotnet test FreeserfNet.sln -c WindowsRelease --no-build --verbosity normal
  - dotnet publish -c WindowsRelease FreeserfNet/FreeserfNet.csproj -p:DefineConstants=WINDOWS -p:PublishSingleFile=true -r win-x64

build:
  project: FreeserfNet.sln

artifacts:
  - path: Freeserf.net-Windows.zip
    name: Freeserf.net-Windows

after_build:
  - 7z a Freeserf.net-Windows.zip "%APPVEYOR_BUILD_FOLDER%\FreeserfNet\bin\Any CPU\WindowsRelease\win-x64\publish\FreeserfNet.exe" "%APPVEYOR_BUILD_FOLDER%\changelog.txt" "%APPVEYOR_BUILD_FOLDER%\FreeserfNet\bass\win-x64\*.dll"

test: off

deploy:
  - provider: GitHub
    name: Freeserf.net-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
