image:
  - Visual Studio 2022
  - Ubuntu2204

for:
-
  matrix:
    only:
      - image: Ubuntu2204

  build_script:
  - dotnet msbuild -p:Configuration=LinuxRelease -p:DefineConstants=LINUX FreeserfNet.sln
  test_script:
  - dotnet test FreeserfNet.sln -c LinuxRelease --no-build --verbosity normal
  after_test:
  - dotnet publish -c LinuxRelease FreeserfNet/FreeserfNet.csproj -p:DefineConstants=LINUX -p:PublishSingleFile=true -r ubuntu-x64
  - 7z a Freeserf.net-Linux.tar "./FreeserfNet/bin/Any CPU/LinuxRelease/ubuntu-x64/publish/FreeserfNet" "./changelog.txt" "./FreeserfNet/bass/linux-x64/*.so"
  - 7z a Freeserf.net-Linux.tar.gz Freeserf.net-Linux.tar -mx9
-
  matrix:
    only:
      - image: Visual Studio 2022

  build_script:
  - dotnet msbuild -p:Configuration=WindowsRelease -p:DefineConstants=WINDOWS FreeserfNet.sln
  test_script:
  - dotnet test FreeserfNet.sln -c WindowsRelease --no-build --verbosity normal
  after_test:
  - dotnet publish -c WindowsRelease FreeserfNet/FreeserfNet.csproj -p:DefineConstants=WINDOWS -p:PublishSingleFile=true -r win-x64
  - 7z a Freeserf.net-Windows.zip "%APPVEYOR_BUILD_FOLDER%\FreeserfNet\bin\Any CPU\WindowsRelease\win-x64\publish\FreeserfNet.exe" "%APPVEYOR_BUILD_FOLDER%\changelog.txt" "%APPVEYOR_BUILD_FOLDER%\FreeserfNet\bass\win-x64\*.dll"

platform: Any CPU

before_build:
  - dotnet restore FreeserfNet.sln --verbosity normal

build:
  parallel: true
  project: FreeserfNet.sln

artifacts:
  - path: Freeserf.net-Windows.zip
    name: Freeserf.net-Windows
  - path: Freeserf.net-Linux.tar.gz
    name: Freeserf.net-Linux

test: on

deploy:
  - provider: GitHub
    name: Freeserf.net-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Freeserf.net-Linux
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
