#!/bin/sh

mkbundle -v --deps --simple Freeserf.net/bin/Release/Freeserf.net.exe -o freeserf.net \
	-L /usr/lib/mono/xbuild/Microsoft/Microsoft.NET.Build.Extensions/net461/lib/ \
	-L Freeserf.Core/release \
	-L Freeserf.Renderer.OpenTK/release \
	-L packages/OpenTK.GLControl.3.0.1/lib/net20/ \
	-L Freeserf.Network/release/ \
	--config /etc/mono/config \
	--machine-config /etc/mono/4.5/machine.config
