name: Build Android APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: conneqthub/dotnet-maui-android:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build Release APK (trimmed)
        run: dotnet build FreeserfNet.Android/FreeserfNet.Android.csproj -f net10.0-android -c Release -p:AndroidPackageFormat=apk -p:PublishTrimmed=true

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: apk-release
          path: FreeserfNet.Android/bin/Release/net10.0-android/*.apk
